-- liquibase formatted sql

-- changeset zakharovanatalia:1
CREATE TABLE IF NOT EXISTS notification_task
(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chatId BIGINT NOT NULL,
    massage TEXT NOT NULL,
    data_time TIMESTAMP NOT NULL
);